#!/usr/bin/env python


import sys
import os

from cbopensource.connectors.threatexchange.bridge import ThreatExchangeConnector
from cbopensource.connectors.threatexchange.version import __version__

if __name__ == "__main__":
    name = "threatexchange"

    # set the path to the CA certificate PEM file to our local cache
    cacert_pem_path = "/usr/share/cb/integrations/threatexchange/cacert.pem"
    if os.path.isfile(cacert_pem_path):
        os.environ["REQUESTS_CA_BUNDLE"] = cacert_pem_path

    daemon = ThreatExchangeConnector(name, configfile="/etc/cb/integrations/threatexchange/connector.conf")

    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        elif 'version' == sys.argv[1]:
            print "%s - version %s" % (name, __version__)
        else:
            print "Unknown command: %s" % sys.argv[1]
            sys.exit(2)

    else:
        print "Usage: %s start|stop|restart|version" % sys.argv[0]
        sys.exit(2)

    sys.exit(0)